import { BarChart3, CheckCircle2, CloudRain, Route } from "lucide-react";

const benchmarkRows = [
  ["CP-SAT optimizer", "91.7%", "0.842", "0.0", "50.1 km"],
  ["Weighted ranker", "91.7%", "0.840", "0.0", "54.0 km"],
  ["Cheapest first", "91.7%", "0.837", "0.0", "52.7 km"],
  ["CP-SAT no weather", "91.7%", "0.785", "1.2", "75.5 km"],
  ["CP-SAT no geospatial", "91.7%", "0.841", "0.0", "52.9 km"],
];

const metricTiles = [
  ["Cases", "12", "Synthetic trips across 10 Indian destinations"],
  ["Systems", "5", "Optimizer, baselines, and two ablations"],
  ["Rows", "60", "Generated by research/experiments/run_all.py"],
];

export function ResearchPage() {
  return (
    <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6">
      <div className="mb-6 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <div className="inline-flex items-center gap-2 rounded-md bg-white px-3 py-2 text-sm font-semibold text-tide shadow-soft">
            <BarChart3 size={16} aria-hidden="true" />
            Benchmark evidence
          </div>
          <h1 className="mt-4 text-3xl font-semibold text-ink">Research results</h1>
        </div>
        <p className="max-w-2xl text-sm leading-6 text-ink/65">
          Results are deterministic synthetic benchmarks, useful for regression checks and ablations rather than claims
          about traveler satisfaction.
        </p>
      </div>

      <section className="grid gap-4 md:grid-cols-3" aria-label="Benchmark summary">
        {metricTiles.map(([label, value, detail]) => (
          <div key={label} className="rounded-lg border border-ink/10 bg-white p-4 shadow-soft">
            <p className="text-sm font-semibold text-tide">{label}</p>
            <p className="mt-2 text-3xl font-semibold text-ink">{value}</p>
            <p className="mt-2 text-sm leading-6 text-ink/65">{detail}</p>
          </div>
        ))}
      </section>

      <section className="mt-6 overflow-hidden rounded-lg border border-ink/10 bg-white shadow-soft">
        <div className="flex items-center gap-2 border-b border-ink/10 px-4 py-3">
          <CheckCircle2 className="text-leaf" size={18} aria-hidden="true" />
          <h2 className="font-semibold text-ink">Latest ablation summary</h2>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full text-left text-sm">
            <thead className="bg-paper text-xs uppercase tracking-wide text-ink/60">
              <tr>
                <th className="px-4 py-3">System</th>
                <th className="px-4 py-3">Feasible</th>
                <th className="px-4 py-3">Mean score</th>
                <th className="px-4 py-3">
                  <span className="inline-flex items-center gap-1">
                    <CloudRain size={14} aria-hidden="true" />
                    Weather conflicts
                  </span>
                </th>
                <th className="px-4 py-3">
                  <span className="inline-flex items-center gap-1">
                    <Route size={14} aria-hidden="true" />
                    Local distance
                  </span>
                </th>
              </tr>
            </thead>
            <tbody>
              {benchmarkRows.map(([system, feasible, score, weather, distance]) => (
                <tr key={system} className="border-t border-ink/10">
                  <td className="px-4 py-3 font-semibold text-ink">{system}</td>
                  <td className="px-4 py-3 text-ink/70">{feasible}</td>
                  <td className="px-4 py-3 text-ink/70">{score}</td>
                  <td className="px-4 py-3 text-ink/70">{weather}</td>
                  <td className="px-4 py-3 text-ink/70">{distance}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </main>
  );
}
